/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_olleb_bad_core_CoreServlet */

#ifndef _Included_com_olleb_bad_core_CoreServlet
#define _Included_com_olleb_bad_core_CoreServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef com_olleb_bad_core_CoreServlet_serialVersionUID
#define com_olleb_bad_core_CoreServlet_serialVersionUID 1LL
/*
 * Class:     com_olleb_bad_core_CoreServlet
 * Method:    core
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_olleb_bad_core_CoreServlet_core
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
